/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: swig_gasdk.i

package greenaddress

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef ptrdiff_t intgo;
typedef size_t uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;

#cgo CFLAGS : -I ./src -I ./ -I gdk/include
#cgo LDFLAGS: -Lgdk/build-gcc-debug -lgreenaddress -Wl,-rpath,gdk/build-gcc-debug

typedef struct GA_json GA_json;
extern void handler_cgo(void*, GA_json*);

typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef _gostring_ swig_type_18;
typedef _gostring_ swig_type_19;
extern void _wrap_Swig_free_greenaddress_f541c850be01f055(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_greenaddress_f541c850be01f055(swig_intgo arg1);
extern void _wrap_go_handler_greenaddress_f541c850be01f055(uintptr_t arg1, swig_type_1 arg2);
extern void _wrap_handler_cgo_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_destroy_json_greenaddress_f541c850be01f055(uintptr_t arg1);
extern swig_intgo _wrap_string_to_json_greenaddress_f541c850be01f055(swig_type_2 arg1, uintptr_t arg2);
extern swig_intgo _wrap_json_to_string_greenaddress_f541c850be01f055(uintptr_t arg1, swig_voidp arg2);
extern swig_intgo _wrap_set_notification_handler_greenaddress_f541c850be01f055(uintptr_t arg1, swig_voidp arg2, uintptr_t arg3);
extern swig_intgo _wrap_GA_ERROR_greenaddress_f541c850be01f055(void);
extern swig_intgo _wrap_GA_RECONNECT_greenaddress_f541c850be01f055(void);
extern swig_intgo _wrap_GA_SESSION_LOST_greenaddress_f541c850be01f055(void);
extern swig_intgo _wrap_GA_TIMEOUT_greenaddress_f541c850be01f055(void);
extern swig_intgo _wrap_GA_NOT_AUTHORIZED_greenaddress_f541c850be01f055(void);
extern swig_intgo _wrap_init_greenaddress_f541c850be01f055(uintptr_t arg1);
extern swig_intgo _wrap_create_session_greenaddress_f541c850be01f055(uintptr_t arg1);
extern swig_intgo _wrap_destroy_session_greenaddress_f541c850be01f055(uintptr_t arg1);
extern swig_intgo _wrap_connect_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_reconnect_hint_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_get_proxy_settings_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_get_wallet_identifier_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_http_request_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_refresh_assets_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_get_assets_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_validate_asset_domain_name_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_validate_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_register_user_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern swig_intgo _wrap_login_user_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern swig_intgo _wrap_set_watch_only_greenaddress_f541c850be01f055(uintptr_t arg1, swig_type_3 arg2, swig_type_4 arg3);
extern swig_intgo _wrap_get_watch_only_username_greenaddress_f541c850be01f055(uintptr_t arg1, swig_voidp arg2);
extern swig_intgo _wrap_remove_account_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_create_subaccount_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_subaccounts_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_subaccount_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_rename_subaccount_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, swig_type_5 arg3);
extern swig_intgo _wrap_update_subaccount_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_transactions_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_receive_address_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_previous_addresses_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_unspent_outputs_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_unspent_outputs_for_private_key_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_set_unspent_outputs_status_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_transaction_details_greenaddress_f541c850be01f055(uintptr_t arg1, swig_type_6 arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_balance_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_available_currencies_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_convert_amount_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_encrypt_with_pin_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_decrypt_with_pin_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_disable_all_pin_logins_greenaddress_f541c850be01f055(uintptr_t arg1);
extern swig_intgo _wrap_create_transaction_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_blind_transaction_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_sign_transaction_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_create_swap_transaction_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_complete_swap_transaction_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_psbt_sign_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_psbt_get_details_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_broadcast_transaction_greenaddress_f541c850be01f055(uintptr_t arg1, swig_type_7 arg2, swig_voidp arg3);
extern swig_intgo _wrap_send_transaction_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_sign_message_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_send_nlocktimes_greenaddress_f541c850be01f055(uintptr_t arg1);
extern swig_intgo _wrap_set_csvtime_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_set_nlocktime_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_set_transaction_memo_greenaddress_f541c850be01f055(uintptr_t arg1, swig_type_8 arg2, swig_type_9 arg3, uintptr_t arg4);
extern swig_intgo _wrap_get_fee_estimates_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_get_credentials_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_system_message_greenaddress_f541c850be01f055(uintptr_t arg1, swig_voidp arg2);
extern swig_intgo _wrap_ack_system_message_greenaddress_f541c850be01f055(uintptr_t arg1, swig_type_10 arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_twofactor_config_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_change_settings_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_settings_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_auth_handler_get_status_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_auth_handler_request_code_greenaddress_f541c850be01f055(uintptr_t arg1, swig_type_11 arg2);
extern swig_intgo _wrap_auth_handler_resolve_code_greenaddress_f541c850be01f055(uintptr_t arg1, swig_type_12 arg2);
extern swig_intgo _wrap_auth_handler_call_greenaddress_f541c850be01f055(uintptr_t arg1);
extern swig_intgo _wrap_destroy_auth_handler_greenaddress_f541c850be01f055(uintptr_t arg1);
extern swig_intgo _wrap_change_settings_twofactor_greenaddress_f541c850be01f055(uintptr_t arg1, swig_type_13 arg2, uintptr_t arg3, uintptr_t arg4);
extern swig_intgo _wrap_twofactor_reset_greenaddress_f541c850be01f055(uintptr_t arg1, swig_type_14 arg2, uintptr_t arg3, uintptr_t arg4);
extern swig_intgo _wrap_twofactor_undo_reset_greenaddress_f541c850be01f055(uintptr_t arg1, swig_type_15 arg2, uintptr_t arg3);
extern swig_intgo _wrap_twofactor_cancel_reset_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_twofactor_change_limits_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_bcur_encode_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_bcur_decode_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_get_random_bytes_greenaddress_f541c850be01f055(swig_type_16 arg1, swig_voidp arg2, swig_type_17 arg3);
extern swig_intgo _wrap_generate_mnemonic_greenaddress_f541c850be01f055(swig_voidp arg1);
extern swig_intgo _wrap_generate_mnemonic_12_greenaddress_f541c850be01f055(swig_voidp arg1);
extern swig_intgo _wrap_validate_mnemonic_greenaddress_f541c850be01f055(swig_type_18 arg1, uintptr_t arg2);
extern swig_intgo _wrap_register_network_greenaddress_f541c850be01f055(swig_type_19 arg1, uintptr_t arg2);
extern swig_intgo _wrap_get_networks_greenaddress_f541c850be01f055(uintptr_t arg1);
extern swig_intgo _wrap_get_uniform_uint32_t_greenaddress_f541c850be01f055(uintptr_t arg1, uintptr_t arg2);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"
import "fmt"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

//export cgo_panic__greenaddress_f541c850be01f055
func cgo_panic__greenaddress_f541c850be01f055(p *byte) {
	s := (*[1024]byte)(unsafe.Pointer(p))[:]
	for i, b := range s {
		if b == 0 {
			panic(string(s[:i]))
		}
	}
	panic(string(s))
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_greenaddress_f541c850be01f055(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Go_handler(arg1 uintptr, arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_go_handler_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Handler_cgo(arg1 uintptr, arg2 Struct_SS_GA_json) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_handler_cgo_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Destroy_json(arg1 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (int)(C._wrap_destroy_json_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func String_to_json(arg1 string, arg2 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_string_to_json_greenaddress_f541c850be01f055(*(*C.swig_type_2)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Json_to_string(arg1 Struct_SS_GA_json, arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_json_to_string_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func Set_notification_handler(arg1 Struct_SS_GA_session, arg2 unsafe.Pointer, arg3 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_set_notification_handler_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}


func GenerateMnemonic() (string, error) {
    var mnemonic string
    r := Generate_mnemonic((*string)(unsafe.Pointer(&mnemonic)))
    if r != 0 {
        // should never be called
        return "", fmt.Errorf("could not genenerate mnemonic: %d", r)
    }
    return mnemonic, nil
}

func GenerateMnemonic12() (string, error) {
    var mnemonic string
    r := Generate_mnemonic_12((*string)(unsafe.Pointer(&mnemonic)))
    if r != 0 {
        return "", fmt.Errorf("could not genenerate mnemonic: %d", r)
    }
    return mnemonic, nil
}

func CreateSession() (Struct_SS_GA_session, error) {
    var p uintptr
    r := Create_session(SwigcptrStruct_SS_GA_session((uintptr)(unsafe.Pointer(&p))))
	if r != 0 {
		return nil, fmt.Errorf("could not convert json to string: %d", r)
	}
	return SwigcptrStruct_SS_GA_session(p), nil
}


type Destroyable_Struct_GA_json interface {
	Struct_SS_GA_json
	Destroy() int
}

type GAJson struct {
	s Struct_SS_GA_json
}

func (p GAJson) Swigcptr() uintptr {
	return p.s.Swigcptr()
}

func (p GAJson) Destroy() int {
	return Destroy_json(p)
}

func ConvertStringToJson(str string) (Destroyable_Struct_GA_json, error) {
    var p uintptr
	r := String_to_json(str, SwigcptrStruct_SS_GA_json((uintptr)(unsafe.Pointer(&p))))
	if r != 0 {
		return nil, fmt.Errorf("could not convert string to json: %d", r)
	}
	return GAJson{s: SwigcptrStruct_SS_GA_json(p)}, nil
}

func ConvertJsonToString(json Struct_SS_GA_json) (string, error) {
    var s string
	r := Json_to_string(json, (*string)(unsafe.Pointer(&s)))
	if r != 0 {
		return "", fmt.Errorf("could not convert json to string: %d", r)
	}
	return s, nil
}

func RegisterUser()


//export go_handler
func go_handler(context unsafe.Pointer, details *C.char) {
    d := C.GoString(details)
    fmt.Printf("details: %s\n", d)
    fmt.Printf("context: %s\n", *(*string)(context))
}

func SetSampleNotificationHandler(session Struct_SS_GA_session, context uintptr) int {
    return Set_notification_handler(session, C.handler_cgo, context)
}

const GA_OK int = 0
func _swig_getGA_ERROR() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GA_ERROR_greenaddress_f541c850be01f055())
	return swig_r
}

var GA_ERROR int = _swig_getGA_ERROR()
func _swig_getGA_RECONNECT() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GA_RECONNECT_greenaddress_f541c850be01f055())
	return swig_r
}

var GA_RECONNECT int = _swig_getGA_RECONNECT()
func _swig_getGA_SESSION_LOST() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GA_SESSION_LOST_greenaddress_f541c850be01f055())
	return swig_r
}

var GA_SESSION_LOST int = _swig_getGA_SESSION_LOST()
func _swig_getGA_TIMEOUT() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GA_TIMEOUT_greenaddress_f541c850be01f055())
	return swig_r
}

var GA_TIMEOUT int = _swig_getGA_TIMEOUT()
func _swig_getGA_NOT_AUTHORIZED() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GA_NOT_AUTHORIZED_greenaddress_f541c850be01f055())
	return swig_r
}

var GA_NOT_AUTHORIZED int = _swig_getGA_NOT_AUTHORIZED()
const GA_NONE int = 0
const GA_INFO int = 1
const GA_DEBUG int = 2
const GA_TRUE int = 1
const GA_FALSE int = 0
func Init(arg1 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (int)(C._wrap_init_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Create_session(arg1 Struct_SS_GA_session) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (int)(C._wrap_create_session_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Destroy_session(arg1 Struct_SS_GA_session) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (int)(C._wrap_destroy_session_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Connect(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_connect_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Reconnect_hint(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_reconnect_hint_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Get_proxy_settings(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_get_proxy_settings_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Get_wallet_identifier(arg1 Struct_SS_GA_json, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_wallet_identifier_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Http_request(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_http_request_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Refresh_assets(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_refresh_assets_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Get_assets(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_assets_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Validate_asset_domain_name(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_validate_asset_domain_name_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Validate(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_validate_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Register_user(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_json, arg4 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	_swig_i_3 := getSwigcptr(arg4)
	swig_r = (int)(C._wrap_register_user_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3)))
	return swig_r
}

func Login_user(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_json, arg4 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	_swig_i_3 := getSwigcptr(arg4)
	swig_r = (int)(C._wrap_login_user_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3)))
	return swig_r
}

func Set_watch_only(arg1 Struct_SS_GA_session, arg2 string, arg3 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_set_watch_only_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Get_watch_only_username(arg1 Struct_SS_GA_session, arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_watch_only_username_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func Remove_account(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_remove_account_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Create_subaccount(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_create_subaccount_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_subaccounts(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_subaccounts_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_subaccount(arg1 Struct_SS_GA_session, arg2 Uint32_t, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_subaccount_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Rename_subaccount(arg1 Struct_SS_GA_session, arg2 Uint32_t, arg3 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_rename_subaccount_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Update_subaccount(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_update_subaccount_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_transactions(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_transactions_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_receive_address(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_receive_address_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_previous_addresses(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_previous_addresses_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_unspent_outputs(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_unspent_outputs_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_unspent_outputs_for_private_key(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_unspent_outputs_for_private_key_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Set_unspent_outputs_status(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_set_unspent_outputs_status_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_transaction_details(arg1 Struct_SS_GA_session, arg2 string, arg3 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_transaction_details_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Get_balance(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_balance_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_available_currencies(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_get_available_currencies_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Convert_amount(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_convert_amount_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Encrypt_with_pin(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_encrypt_with_pin_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Decrypt_with_pin(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_decrypt_with_pin_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Disable_all_pin_logins(arg1 Struct_SS_GA_session) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (int)(C._wrap_disable_all_pin_logins_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Create_transaction(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_create_transaction_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Blind_transaction(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_blind_transaction_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Sign_transaction(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_sign_transaction_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Create_swap_transaction(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_create_swap_transaction_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Complete_swap_transaction(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_complete_swap_transaction_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Psbt_sign(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_psbt_sign_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Psbt_get_details(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_psbt_get_details_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Broadcast_transaction(arg1 Struct_SS_GA_session, arg2 string, arg3 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_broadcast_transaction_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Send_transaction(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_send_transaction_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Sign_message(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_sign_message_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Send_nlocktimes(arg1 Struct_SS_GA_session) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (int)(C._wrap_send_nlocktimes_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Set_csvtime(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_set_csvtime_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Set_nlocktime(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_set_nlocktime_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Set_transaction_memo(arg1 Struct_SS_GA_session, arg2 string, arg3 string, arg4 Uint32_t) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := getSwigcptr(arg4)
	swig_r = (int)(C._wrap_set_transaction_memo_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), *(*C.swig_type_8)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_9)(unsafe.Pointer(&_swig_i_2)), C.uintptr_t(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Get_fee_estimates(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_get_fee_estimates_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Get_credentials(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_get_credentials_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_system_message(arg1 Struct_SS_GA_session, arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_system_message_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func Ack_system_message(arg1 Struct_SS_GA_session, arg2 string, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_ack_system_message_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), *(*C.swig_type_10)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Get_twofactor_config(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_get_twofactor_config_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Change_settings(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_change_settings_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_settings(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_get_settings_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Auth_handler_get_status(arg1 Struct_SS_GA_auth_handler, arg2 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_auth_handler_get_status_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Auth_handler_request_code(arg1 Struct_SS_GA_auth_handler, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_auth_handler_request_code_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), *(*C.swig_type_11)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Auth_handler_resolve_code(arg1 Struct_SS_GA_auth_handler, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_auth_handler_resolve_code_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), *(*C.swig_type_12)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Auth_handler_call(arg1 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (int)(C._wrap_auth_handler_call_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Destroy_auth_handler(arg1 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (int)(C._wrap_destroy_auth_handler_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Change_settings_twofactor(arg1 Struct_SS_GA_session, arg2 string, arg3 Struct_SS_GA_json, arg4 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	_swig_i_2 := getSwigcptr(arg3)
	_swig_i_3 := getSwigcptr(arg4)
	swig_r = (int)(C._wrap_change_settings_twofactor_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), *(*C.swig_type_13)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Twofactor_reset(arg1 Struct_SS_GA_session, arg2 string, arg3 Uint32_t, arg4 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	_swig_i_2 := getSwigcptr(arg3)
	_swig_i_3 := getSwigcptr(arg4)
	swig_r = (int)(C._wrap_twofactor_reset_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), *(*C.swig_type_14)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Twofactor_undo_reset(arg1 Struct_SS_GA_session, arg2 string, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_twofactor_undo_reset_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), *(*C.swig_type_15)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Twofactor_cancel_reset(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_twofactor_cancel_reset_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Twofactor_change_limits(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_twofactor_change_limits_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Bcur_encode(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_bcur_encode_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Bcur_decode(arg1 Struct_SS_GA_session, arg2 Struct_SS_GA_json, arg3 Struct_SS_GA_auth_handler) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := getSwigcptr(arg3)
	swig_r = (int)(C._wrap_bcur_decode_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Get_random_bytes(arg1 int64, arg2 *byte, arg3 int64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_get_random_bytes_greenaddress_f541c850be01f055(C.swig_type_16(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_type_17(_swig_i_2)))
	return swig_r
}

func Generate_mnemonic(arg1 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_generate_mnemonic_greenaddress_f541c850be01f055(C.swig_voidp(_swig_i_0)))
	return swig_r
}

func Generate_mnemonic_12(arg1 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_generate_mnemonic_12_greenaddress_f541c850be01f055(C.swig_voidp(_swig_i_0)))
	return swig_r
}

func Validate_mnemonic(arg1 string, arg2 Uint32_t) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_validate_mnemonic_greenaddress_f541c850be01f055(*(*C.swig_type_18)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Register_network(arg1 string, arg2 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_register_network_greenaddress_f541c850be01f055(*(*C.swig_type_19)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Get_networks(arg1 Struct_SS_GA_json) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (int)(C._wrap_get_networks_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Get_uniform_uint32_t(arg1 Uint32_t, arg2 Uint32_t) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (int)(C._wrap_get_uniform_uint32_t_greenaddress_f541c850be01f055(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}


type SwigcptrStruct_SS_GA_auth_handler uintptr
type Struct_SS_GA_auth_handler interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_GA_auth_handler) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint32_t uintptr
type Uint32_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint32_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_GA_json uintptr
type Struct_SS_GA_json interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_GA_json) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_GA_session uintptr
type Struct_SS_GA_session interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_GA_session) Swigcptr() uintptr {
	return uintptr(p)
}

