/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: swig_gasdk.i */


extern
#ifdef __cplusplus
  "C"
#endif
  void cgo_panic__greenaddress_f541c850be01f055(const char*);
static void _swig_gopanic(const char *p) {
  cgo_panic__greenaddress_f541c850be01f055(p);
}



#define SWIG_VERSION 0x040101
#define SWIGGO
#define SWIGMODULE greenaddress
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef ptrdiff_t intgo;
typedef size_t uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#define SWIG_exception(code, msg) _swig_gopanic(msg)


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "gdk/include/gdk.h"

    void debug_print_chars(const char* in)
    {
        printf("%s\n", in);
        fflush(stdout);
    }

    void debug_print_GA_json(const GA_json* in)
    {
        printf("%p\n", in);
        fflush(stdout);
    }

    static int destroy_json(GA_json * json) { return GA_destroy_json(json); }

    static int string_to_json(char* in, struct GA_json** out) { return GA_convert_string_to_json(in, out); }
    
    static int json_to_string(const GA_json* json, char** out) { return GA_convert_json_to_string(json, out); }

    static int set_notification_handler(struct GA_session* session, void* handler, void* context)
    {
        return GA_set_notification_handler(session, handler, context);
    }


extern void go_handler(void*, char*);

void handler_cgo(void* context, GA_json* details) {
    char* out = (char*) 0;
    int result;

    if (details) {
      result = json_to_string(details, &out);
      if (result != GA_OK) {
          return;
      }
    }
  
    go_handler(context, out);
    GA_destroy_json(details);
    GA_destroy_string(out);
}

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_greenaddress_f541c850be01f055(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_greenaddress_f541c850be01f055(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_go_handler_greenaddress_f541c850be01f055(void *_swig_go_0, _gostring_ _swig_go_1) {
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  go_handler(arg1,arg2);
  
  free(arg2); 
}


void _wrap_handler_cgo_greenaddress_f541c850be01f055(void *_swig_go_0, struct GA_json *_swig_go_1) {
  void *arg1 = (void *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  
  handler_cgo(arg1,arg2);
  
}


intgo _wrap_destroy_json_greenaddress_f541c850be01f055(struct GA_json *_swig_go_0) {
  GA_json *arg1 = (GA_json *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GA_json **)&_swig_go_0; 
  
  result = (int)destroy_json(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_string_to_json_greenaddress_f541c850be01f055(_gostring_ _swig_go_0, struct GA_json **_swig_go_1) {
  char *arg1 = (char *) 0 ;
  struct GA_json **arg2 = (struct GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = *(struct GA_json ***)&_swig_go_1; 
  
  result = (int)string_to_json(arg1,arg2);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_json_to_string_greenaddress_f541c850be01f055(struct GA_json *_swig_go_0, _gostring_* _swig_go_1) {
  GA_json *arg1 = (GA_json *) 0 ;
  char **arg2 = (char **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GA_json **)&_swig_go_0; 
  arg2 = *(char ***)&_swig_go_1; 
  
  result = (int)json_to_string((struct GA_json const *)arg1,arg2);
  _swig_go_result = result; 
  {
    if (arg2 && *arg2) {
      _swig_go_1->n = strlen(*arg2);
    }
  }
  return _swig_go_result;
}


intgo _wrap_set_notification_handler_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, void *_swig_go_1, void *_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  void *arg2 = (void *) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  result = (int)set_notification_handler(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GA_ERROR_greenaddress_f541c850be01f055() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)((-1));
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GA_RECONNECT_greenaddress_f541c850be01f055() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)((-2));
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GA_SESSION_LOST_greenaddress_f541c850be01f055() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)((-3));
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GA_TIMEOUT_greenaddress_f541c850be01f055() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)((-4));
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_GA_NOT_AUTHORIZED_greenaddress_f541c850be01f055() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)((-5));
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_init_greenaddress_f541c850be01f055(struct GA_json *_swig_go_0) {
  GA_json *arg1 = (GA_json *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GA_json **)&_swig_go_0; 
  
  result = (int)GA_init((struct GA_json const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_create_session_greenaddress_f541c850be01f055(struct GA_session **_swig_go_0) {
  struct GA_session **arg1 = (struct GA_session **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session ***)&_swig_go_0; 
  
  result = (int)GA_create_session(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_destroy_session_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  result = (int)GA_destroy_session(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_connect_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  
  result = (int)GA_connect(arg1,(struct GA_json const *)arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_reconnect_hint_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  
  result = (int)GA_reconnect_hint(arg1,(struct GA_json const *)arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_proxy_settings_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json **_swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json **arg2 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json ***)&_swig_go_1; 
  
  result = (int)GA_get_proxy_settings(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_wallet_identifier_greenaddress_f541c850be01f055(struct GA_json *_swig_go_0, struct GA_json *_swig_go_1, struct GA_json **_swig_go_2) {
  GA_json *arg1 = (GA_json *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  GA_json **arg3 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GA_json **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(GA_json ***)&_swig_go_2; 
  
  result = (int)GA_get_wallet_identifier((struct GA_json const *)arg1,(struct GA_json const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_http_request_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_json **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  GA_json **arg3 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(GA_json ***)&_swig_go_2; 
  
  result = (int)GA_http_request(arg1,(struct GA_json const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_refresh_assets_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  
  result = (int)GA_refresh_assets(arg1,(struct GA_json const *)arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_assets_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_json **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  GA_json **arg3 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(GA_json ***)&_swig_go_2; 
  
  result = (int)GA_get_assets(arg1,(struct GA_json const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_validate_asset_domain_name_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_json **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  GA_json **arg3 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(GA_json ***)&_swig_go_2; 
  
  result = (int)GA_validate_asset_domain_name(arg1,(struct GA_json const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_validate_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_validate(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_register_user_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_json *_swig_go_2, struct GA_auth_handler **_swig_go_3) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  GA_json *arg3 = (GA_json *) 0 ;
  struct GA_auth_handler **arg4 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(GA_json **)&_swig_go_2; 
  arg4 = *(struct GA_auth_handler ***)&_swig_go_3; 
  
  result = (int)GA_register_user(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_login_user_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_json *_swig_go_2, struct GA_auth_handler **_swig_go_3) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  GA_json *arg3 = (GA_json *) 0 ;
  struct GA_auth_handler **arg4 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(GA_json **)&_swig_go_2; 
  arg4 = *(struct GA_auth_handler ***)&_swig_go_3; 
  
  result = (int)GA_login_user(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_set_watch_only_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  result = (int)GA_set_watch_only(arg1,(char const *)arg2,(char const *)arg3);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_get_watch_only_username_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, _gostring_* _swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  char **arg2 = (char **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(char ***)&_swig_go_1; 
  
  result = (int)GA_get_watch_only_username(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_remove_account_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_auth_handler **_swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  struct GA_auth_handler **arg2 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(struct GA_auth_handler ***)&_swig_go_1; 
  
  result = (int)GA_remove_account(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_create_subaccount_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_create_subaccount(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_subaccounts_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_get_subaccounts(arg1,(struct GA_json const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_subaccount_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, uint32_t *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  uint32_t arg2 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  uint32_t *argp2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  argp2 = (uint32_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null uint32_t");
  }
  arg2 = (uint32_t)*argp2;
  
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_get_subaccount(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_rename_subaccount_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, uint32_t *_swig_go_1, _gostring_ _swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  uint32_t arg2 ;
  char *arg3 = (char *) 0 ;
  uint32_t *argp2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  argp2 = (uint32_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null uint32_t");
  }
  arg2 = (uint32_t)*argp2;
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  result = (int)GA_rename_subaccount(arg1,arg2,(char const *)arg3);
  _swig_go_result = result; 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_update_subaccount_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_update_subaccount(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_transactions_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_get_transactions(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_receive_address_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_get_receive_address(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_previous_addresses_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_get_previous_addresses(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_unspent_outputs_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_get_unspent_outputs(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_unspent_outputs_for_private_key_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_get_unspent_outputs_for_private_key(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_set_unspent_outputs_status_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_set_unspent_outputs_status(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_transaction_details_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, _gostring_ _swig_go_1, struct GA_json **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  char *arg2 = (char *) 0 ;
  GA_json **arg3 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(GA_json ***)&_swig_go_2; 
  
  result = (int)GA_get_transaction_details(arg1,(char const *)arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_get_balance_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_get_balance(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_available_currencies_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json **_swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json **arg2 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json ***)&_swig_go_1; 
  
  result = (int)GA_get_available_currencies(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_convert_amount_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_json **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  GA_json **arg3 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(GA_json ***)&_swig_go_2; 
  
  result = (int)GA_convert_amount(arg1,(struct GA_json const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_encrypt_with_pin_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_encrypt_with_pin(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_decrypt_with_pin_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_decrypt_with_pin(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_disable_all_pin_logins_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  result = (int)GA_disable_all_pin_logins(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_create_transaction_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_create_transaction(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_blind_transaction_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_blind_transaction(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sign_transaction_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_sign_transaction(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_create_swap_transaction_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_create_swap_transaction(arg1,(struct GA_json const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_complete_swap_transaction_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_complete_swap_transaction(arg1,(struct GA_json const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_psbt_sign_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_psbt_sign(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_psbt_get_details_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_psbt_get_details(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_broadcast_transaction_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, _gostring_ _swig_go_1, _gostring_* _swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  char *arg2 = (char *) 0 ;
  char **arg3 = (char **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(char ***)&_swig_go_2; 
  
  result = (int)GA_broadcast_transaction(arg1,(char const *)arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_send_transaction_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_send_transaction(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_sign_message_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_sign_message(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_send_nlocktimes_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  result = (int)GA_send_nlocktimes(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_set_csvtime_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_set_csvtime(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_set_nlocktime_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_set_nlocktime(arg1,(struct GA_json const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_set_transaction_memo_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, uint32_t *_swig_go_3) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  uint32_t arg4 ;
  uint32_t *argp4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  argp4 = (uint32_t *)_swig_go_3;
  if (argp4 == NULL) {
    _swig_gopanic("Attempt to dereference null uint32_t");
  }
  arg4 = (uint32_t)*argp4;
  
  
  result = (int)GA_set_transaction_memo(arg1,(char const *)arg2,(char const *)arg3,arg4);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_get_fee_estimates_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json **_swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json **arg2 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json ***)&_swig_go_1; 
  
  result = (int)GA_get_fee_estimates(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_credentials_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_get_credentials(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_system_message_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, _gostring_* _swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  char **arg2 = (char **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(char ***)&_swig_go_1; 
  
  result = (int)GA_get_system_message(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ack_system_message_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, _gostring_ _swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  char *arg2 = (char *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_ack_system_message(arg1,(char const *)arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_get_twofactor_config_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json **_swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json **arg2 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json ***)&_swig_go_1; 
  
  result = (int)GA_get_twofactor_config(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_change_settings_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_change_settings(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_settings_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json **_swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json **arg2 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json ***)&_swig_go_1; 
  
  result = (int)GA_get_settings(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_auth_handler_get_status_greenaddress_f541c850be01f055(struct GA_auth_handler *_swig_go_0, struct GA_json **_swig_go_1) {
  struct GA_auth_handler *arg1 = (struct GA_auth_handler *) 0 ;
  GA_json **arg2 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_auth_handler **)&_swig_go_0; 
  arg2 = *(GA_json ***)&_swig_go_1; 
  
  result = (int)GA_auth_handler_get_status(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_auth_handler_request_code_greenaddress_f541c850be01f055(struct GA_auth_handler *_swig_go_0, _gostring_ _swig_go_1) {
  struct GA_auth_handler *arg1 = (struct GA_auth_handler *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_auth_handler **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)GA_auth_handler_request_code(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_auth_handler_resolve_code_greenaddress_f541c850be01f055(struct GA_auth_handler *_swig_go_0, _gostring_ _swig_go_1) {
  struct GA_auth_handler *arg1 = (struct GA_auth_handler *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_auth_handler **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)GA_auth_handler_resolve_code(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_auth_handler_call_greenaddress_f541c850be01f055(struct GA_auth_handler *_swig_go_0) {
  struct GA_auth_handler *arg1 = (struct GA_auth_handler *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_auth_handler **)&_swig_go_0; 
  
  result = (int)GA_auth_handler_call(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_destroy_auth_handler_greenaddress_f541c850be01f055(struct GA_auth_handler *_swig_go_0) {
  struct GA_auth_handler *arg1 = (struct GA_auth_handler *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_auth_handler **)&_swig_go_0; 
  
  result = (int)GA_destroy_auth_handler(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_change_settings_twofactor_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, _gostring_ _swig_go_1, struct GA_json *_swig_go_2, struct GA_auth_handler **_swig_go_3) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  char *arg2 = (char *) 0 ;
  GA_json *arg3 = (GA_json *) 0 ;
  struct GA_auth_handler **arg4 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(GA_json **)&_swig_go_2; 
  arg4 = *(struct GA_auth_handler ***)&_swig_go_3; 
  
  result = (int)GA_change_settings_twofactor(arg1,(char const *)arg2,arg3,arg4);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_twofactor_reset_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, _gostring_ _swig_go_1, uint32_t *_swig_go_2, struct GA_auth_handler **_swig_go_3) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  char *arg2 = (char *) 0 ;
  uint32_t arg3 ;
  struct GA_auth_handler **arg4 = (struct GA_auth_handler **) 0 ;
  uint32_t *argp3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  argp3 = (uint32_t *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null uint32_t");
  }
  arg3 = (uint32_t)*argp3;
  
  arg4 = *(struct GA_auth_handler ***)&_swig_go_3; 
  
  result = (int)GA_twofactor_reset(arg1,(char const *)arg2,arg3,arg4);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_twofactor_undo_reset_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, _gostring_ _swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  char *arg2 = (char *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_twofactor_undo_reset(arg1,(char const *)arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_twofactor_cancel_reset_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_auth_handler **_swig_go_1) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  struct GA_auth_handler **arg2 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(struct GA_auth_handler ***)&_swig_go_1; 
  
  result = (int)GA_twofactor_cancel_reset(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_twofactor_change_limits_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_twofactor_change_limits(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_bcur_encode_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_bcur_encode(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_bcur_decode_greenaddress_f541c850be01f055(struct GA_session *_swig_go_0, struct GA_json *_swig_go_1, struct GA_auth_handler **_swig_go_2) {
  struct GA_session *arg1 = (struct GA_session *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  struct GA_auth_handler **arg3 = (struct GA_auth_handler **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct GA_session **)&_swig_go_0; 
  arg2 = *(GA_json **)&_swig_go_1; 
  arg3 = *(struct GA_auth_handler ***)&_swig_go_2; 
  
  result = (int)GA_bcur_decode(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_random_bytes_greenaddress_f541c850be01f055(long long _swig_go_0, char *_swig_go_1, long long _swig_go_2) {
  size_t arg1 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  size_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  arg2 = *(unsigned char **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  result = (int)GA_get_random_bytes(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_generate_mnemonic_greenaddress_f541c850be01f055(_gostring_* _swig_go_0) {
  char **arg1 = (char **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(char ***)&_swig_go_0; 
  
  result = (int)GA_generate_mnemonic(arg1);
  _swig_go_result = result; 
  {
    if (arg1 && *arg1) {
      _swig_go_0->n = strlen(*arg1);
    }
  }
  return _swig_go_result;
}


intgo _wrap_generate_mnemonic_12_greenaddress_f541c850be01f055(_gostring_* _swig_go_0) {
  char **arg1 = (char **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(char ***)&_swig_go_0; 
  
  result = (int)GA_generate_mnemonic_12(arg1);
  _swig_go_result = result; 
  {
    if (arg1 && *arg1) {
      _swig_go_0->n = strlen(*arg1);
    }
  }
  return _swig_go_result;
}


intgo _wrap_validate_mnemonic_greenaddress_f541c850be01f055(_gostring_ _swig_go_0, uint32_t *_swig_go_1) {
  char *arg1 = (char *) 0 ;
  uint32_t *arg2 = (uint32_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = *(uint32_t **)&_swig_go_1; 
  
  result = (int)GA_validate_mnemonic((char const *)arg1,arg2);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_register_network_greenaddress_f541c850be01f055(_gostring_ _swig_go_0, struct GA_json *_swig_go_1) {
  char *arg1 = (char *) 0 ;
  GA_json *arg2 = (GA_json *) 0 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = *(GA_json **)&_swig_go_1; 
  
  result = (int)GA_register_network((char const *)arg1,(struct GA_json const *)arg2);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_get_networks_greenaddress_f541c850be01f055(struct GA_json **_swig_go_0) {
  GA_json **arg1 = (GA_json **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GA_json ***)&_swig_go_0; 
  
  result = (int)GA_get_networks(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_uniform_uint32_t_greenaddress_f541c850be01f055(uint32_t *_swig_go_0, uint32_t *_swig_go_1) {
  uint32_t arg1 ;
  uint32_t *arg2 = (uint32_t *) 0 ;
  uint32_t *argp1 ;
  int result;
  intgo _swig_go_result;
  
  
  argp1 = (uint32_t *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null uint32_t");
  }
  arg1 = (uint32_t)*argp1;
  
  arg2 = *(uint32_t **)&_swig_go_1; 
  
  result = (int)GA_get_uniform_uint32_t(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

